# Generated by Django 5.2.13 on 2026-04-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('team_leader', models.CharField(blank=True, max_length=200)),
                ('department_head', models.CharField(blank=True, max_length=200)),
                ('team_type', models.CharField(blank=True, max_length=100)),
                ('mission', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('slack_channel', models.CharField(blank=True, max_length=200)),
                ('code_repository', models.URLField(blank=True)),
                ('jira_board', models.URLField(blank=True)),
                ('wiki_page', models.URLField(blank=True)),
                ('upstream_dependencies', models.TextField(blank=True)),
                ('downstream_dependencies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
        ),
    ]
